worker_processes auto;
pid /run/nginx/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

user www-data www-data;

events {
    worker_connections 768;
}

http {
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;

    include /etc/nginx/conf.d/*.conf;

    server {
        server_name _;
        listen 0.0.0.0:8000;

        # API requests go to Symfony/PHP
        location /api {
            root /srv/app/public;
            try_files $uri /index.php$is_args$args;
        }

        location ~ ^/index\.php(/|$) {
            root /srv/app/public;
            fastcgi_pass unix:/run/php/php8.0-fpm.sock;
            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME /srv/app/public$fastcgi_script_name;
            fastcgi_param DOCUMENT_ROOT /srv/app/public;
            internal;
        }

        # Vue.js static files
        root /srv/app/frontend/dist;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location ~ \.php$ {
            return 404;
        }
    }
}
