name: Test

on: [push]

env:
  APP_ENV: test
  DATABASE_URL: mysql://root:symfony@127.0.0.1:13306/app?serverVersion=8.0

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      database:
        image: mysql/mysql-server:8.0
        env:
          MYSQL_DATABASE: app
          MYSQL_USER: symfony
          MYSQL_PASSWORD: symfony
          MYSQL_ROOT_PASSWORD: symfony
          MYSQL_ROOT_HOST: '%'
        ports:
          - 13306:3306
        options: >-
          --memory=2g
          --health-cmd="mysqladmin --password=symfony ping"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=3
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mysqli, pdo, pdo_mysql
          tools: composer:2.2

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress

      - name: Create test database
        run: php bin/console --env=test doctrine:database:create --no-interaction

      - name: Run database migrations
        run: php bin/console --env=test doctrine:migrations:migrate --no-interaction

      - name: Create database fixtures
        run: php bin/console --env=test doctrine:fixtures:load --no-interaction

      - name: Run PHPUnit tests
        run: php vendor/bin/phpunit tests/
